### ISSUE TITLE
Plot missing data feature

### ISSUE THREAD

**Issue by lucazav** [choonghyunryu/dlookr#14]
It’s often useful to understand if missing values of a feature are related to the missing ones of another feature. In this case an [UpSet plot](https://jokergoo.github.io/ComplexHeatmap-reference/book/upset-plot.html) for missing values would be a great add to this wonderful package.

Here some examples: [Gallery of Missing Data Visualisations](https://cran.r-project.org/web/packages/naniar/vignettes/naniar-visualisation.html)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by choonghyunryu** [comment]
@lucazav 
Thanks for the great feature suggestion.
I will add the features you suggested to the next version.

If you need any improvements in this package, or if you have any features you would like to add, please do not hesitate to tell us.

Thanks and Best Regards,
Choonghyun

**Comment by choonghyunryu** [comment]
@lucazav
A lot of time has passed, but I have just put the output of your proposal into the package.

plot_na_intersect() is a function that draws a plot similar to gg_miss_upset() in the naniar package. And in addition I added the plot_na_pareto() function and the plot_na_hclust() function.
It is only on github yet, not on CRAN.

I've been concerned about your health since you helped my package. Are you healthy?

I will gradually develop the rest of the features you suggested.
Always healthy and good luck.

Thanks and Best Regards,
Choonghyun

**Comment by lucazav** [comment]
Hi @choonghyunryu ,

thank you for your feedback. Fortunately I'm healthy and I hope you're healthy too.

Looking forward for new developments!

Regards.

**Comment by choonghyunryu** [comment]
Hi @lucazav ,

This issue is closed.

Thanks and Best Regards,
Choonghyun
