### ISSUE TITLE
diagnose_report() is not working 

### ISSUE THREAD

**Issue by DrAlqahtani** [choonghyunryu/dlookr#24]
diagnose_report() is not working. The reason is that some of the values in Arabic and I do think the issue when the code try to compile latex file with Arabic

**Comment by choonghyunryu** [comment]
@DrAlqahtani 

Currently, the pdf output from the dlookr package's reporting function uses latex.
And this function only supports English and Korean.

The problem of not supporting other characters like Arabic is due to the problem of latex, not the problem of R.
And it is difficult to find a solution because I cannot reproduce the data of the characters of other countries.

In the next version I will find a solution with the ability for users to add latex packages. Sorry, please use the html report until then.

Thanks and best greards,
Ryu

**Comment by choonghyunryu** [comment]
@DrAlqahtani

Try using the 0.5.0 version of diagnose_paged_report(), diagnose_web_report(). If an error occurs in Arabic problem, please give feedback.
