### ISSUE TITLE
reportData error in eda_paged_report

### ISSUE THREAD

**Issue by emantzo** [choonghyunryu/dlookr#54]
Hi
I am trying to use `eda_paged_report` with a dataset but I get the error: 
```
Quitting from lines 170-173 (eda_paged_temp.Rmd) 
Error in is.data.frame(df) : object 'reportData' not found

```

I am using the last version from CRAN.
Thank you!

**Comment by choonghyunryu** [comment]
Hi @emantzo 

Thanks for reporting the problem.

I also found the problem and already posted an error-fixed version on github.
Use the github version to use the one that solves the problem.

It's been a while since I uploaded a patched version of a minor issue to CRAN, so I'll have to wait a few days to upload a patched version.
I will also submit a modified version to CRAN soon.

Thanks and Best Regards,
Choonghyun

**Comment by emantzo** [comment]
Thank you for your prompt reply and many thanks for this super pack!

**Comment by choonghyunryu** [comment]
Close issue because fixed problem
