### ISSUE TITLE
add group_by() functionality

### ISSUE THREAD

**Issue by jyk** [choonghyunryu/dlookr#90]
Hi, maybe I am missing something, but I can not use currently group_by() and then diagnose() etc. Is it possible please to add this functionality ("diagnose for groups") ?

**Comment by choonghyunryu** [comment]
@jyk,
Thank you for your suggestions.

Currently diagnose() does not support group_by().

describe(), correlate(), and normality() for EDA support group_by, but operations in the Data Diagnosis task do not support group_by(). This is because it is designed for the purpose of diagnosing data when you first encounter it.

By the way,  I think your attempt is meaningful.
This is because the quality of the data can be problematic in certain categories.

I will modify diagnose() to work with group_by().
just give me some time

**Comment by jyk** [comment]
Thanks. Yes, I would like to use group_by() for different time periods (like in weekly and monthly basis) in order to track the data quality issues in time

**Comment by choonghyunryu** [comment]
@jyk,

I implemented your suggestions on github development version 0.6.2.9000.

Functions that support group_by() are as follows.:

- diagnose()
- diagnose_category()
- diagnose_numeric()
- diagnose_outlier()
   
 Thanks

**Comment by jyk** [comment]
Thank You very much! Now I am fine.

**Comment by lorenzoFabbri** [comment]
I wrote a function which takes as input a string (in this specific case "cohort") representing a factor to pass to `dplyr::group_by`, which is called before `diagnose_category`:

```
dlookr::diagnose_category(dat |> dplyr::group_by({{ grouping_var }}))
```

It does not produce any error but in the resulting tibble, the column `cohort` contains only the value `cohort`, rather than its levels. I guess it is related to the use of `{{`, but I have not found a solution.

**Comment by choonghyunryu** [comment]
Dear Lorenzo Fabbri,

Pass arguments to the group_by() function with the across() function, as in the following example.

grouping_var <- "death_event" 
dlookr::heartfailure |>  
    group_by(across(all_of(grouping_var))) |>  
    dlookr::diagnose_category()

Regards,
choonghyun

-----Original Message-----
